export const products = [
    {
        id: 1,
        name: "Apple iPhone 14 Pro Max 128GB Deep Purple (MQ9T3RX/A)",
        description: 'Experience next-generation performance with the iPhone 14 Pro Max. Boasting a 128GB storage capacity and a stunning deep purple finish, this model captures the essence of innovation and style.',
        price: 900,
        image: "/images/productImage/iphone14.png",
        like: true,
    },
    {
        id: 2,
        name: "Blackmagic Pocket Cinema Camera 6k",
        description: 'Unleash cinematic brilliance with the Blackmagic Pocket Cinema Camera 6k. Designed for filmmakers, this compact camera delivers 6K resolution for breathtaking image quality.',
        price: 2535,
        image: "/images/productImage/camera.png",
        like: true,
    },
    {
        id: 3,
        name: "Apple Watch Series 9 GPS 41mm Starlight Aluminium Case",
        description: 'Elevate your style and fitness with the Apple Watch Series 9. The 41mm starlight aluminium case is both elegant and durable, keeping you connected and active all day long.',
        price: 399,
        image: "/images/productImage/applewatch.png",
        like: true,
    },
    {
        id: 4,
        name: "AirPods Max Silver",
        description: 'Immerse yourself in high-fidelity audio with the AirPods Max Silver. Featuring active noise cancellation and spatial audio, they redefine the listening experience.',
        price: 549,
        image: "/images/productImage/headphone.png",
        like: true,
    },
    {
        id: 5,
        name: "Samsung Galaxy Watch6 Classic 47mm Black",
        description: 'Classic design meets modern technology with the Samsung Galaxy Watch6 Classic. This 47mm smartwatch in black is the perfect blend of style and functionality for your wrist.',
        price: 369,
        image: "/images/productImage/samsungwatch.png",
        like: false,
    },
    {
        id: 6,
        name: "Galaxy Z Fold5 Unlocked | 256GB | Phantom Black",
        description: 'Discover the future of smartphones with the Galaxy Z Fold5. Featuring a foldable display and 256GB of storage, this unlocked phantom black device is a powerhouse of innovation.',
        price: 1799,
        image: "/images/productImage/galaxyzfold.png",
        like: false,
    },
    {
        id: 7,
        name: "Galaxy Buds FEGraphite",
        description: 'Step into a world of sound with the Galaxy Buds FE in graphite. These wireless earbuds offer crystal-clear audio and a comfortable fit for all-day listening.',
        price: 99.99,
        image: "/images/productImage/galaxybuds.png",
        like: false,
    },
    {
        id: 8,
        name: 'Apple iPad 9 10.2" 64GB Wi-Fi Silver (MK2L3) 2021',
        description: 'Enhance your productivity and entertainment with the Apple iPad 9. This 10.2" tablet packs 64GB of storage, Wi-Fi connectivity, and a sleek silver design into one powerful device.',
        price: 398,
        image: "/images/productImage/appleipad.png",
        like: true,
    },
];